"""created db structure

Revision ID: 55d2bf274509
Revises: 1f3303fa65d2
Create Date: 2021-08-03 10:13:37.247668

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55d2bf274509'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # CREATE TABLE "action" (
    #   "status" varchar PRIMARY KEY
    # );
    action_table = op.create_table('action', sa.Column('status', sa.String(), nullable=False, primary_key=True))
    op.bulk_insert(action_table, [{'status': 'initial'},{'status': 'retry'},{'status': 'delete'},])

    # CREATE TABLE "parser" (
    #   "name" varchar PRIMARY KEY
    #   "source_filename" varchar,
    # );
    parser_table = op.create_table('parser',
                                   sa.Column('name', sa.String(), nullable=False, primary_key=True),
                                   sa.Column('extension_pattern', sa.String(), nullable=False),
                                   sa.Column('reference_service_endpoint', sa.String(), nullable=False),
                                   sa.Column('matches', postgresql.JSONB(), nullable=True),
    )
    op.create_index('extension_pattern_fk_idx', 'parser', ['extension_pattern'])

    op.bulk_insert(parser_table, [
        {'name': 'AAS', 'extension_pattern': '.raw', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal": "AJ", "volume_begin": 115, "volume_end": 134},{"journal": "ApJ", "volume_begin": 474, "volume_end": 689},
            {"journal": "ApJL", "volume_begin": 1, "volume_end": 689},{"journal": "ApJS", "volume_begin": 108, "volume_end": 179},
        ]},
        {'name': 'ADSocr', 'extension_pattern': '.ocr.txt', 'reference_service_endpoint': '/text', 'matches': [
            {"journal":"A&A", "all_volume":True},{"journal":"A&ARv", "volume_begin":1, "volume_end":169},
            {"journal":"A&AS", "all_volume":True},{"journal":"AAM", "volume_begin":1, "volume_end":169},
            {"journal":"AAnST", "volume_begin":1, "volume_end":169},{"journal":"AcA", "volume_begin":1, "volume_end":48},
            {"journal":"AcGeo", "volume_begin":1, "volume_end":169},{"journal":"AcMSn", "volume_begin":1, "volume_end":169},
            {"journal":"AcSSn", "volume_begin":1, "volume_end":169},{"journal":"AdAer", "volume_begin":1, "volume_end":169},
            {"journal":"AdAtS", "volume_begin":1, "volume_end":169},{"journal":"AeMiS", "volume_begin":1, "volume_end":169},
            {"journal":"AerSE", "volume_begin":1, "volume_end":169},{"journal":"AerSy", "volume_begin":1, "volume_end":169},
            {"journal":"AJ", "volume_begin":1, "volume_end":114},{"journal":"AMGBA", "volume_begin":1, "volume_end":169},
            {"journal":"AMGBB", "volume_begin":1, "volume_end":169},{"journal":"AnHP", "volume_begin":1, "volume_end":169},
            {"journal":"AnSSM", "volume_begin":1, "volume_end":169},{"journal":"Ap", "volume_begin":1, "volume_end":169},
            {"journal":"Ap&SS", "volume_begin":1, "volume_end":246},{"journal":"Ap+SS", "volume_begin":1, "volume_end":169},
            {"journal":"ApCM", "volume_begin":1, "volume_end":169},{"journal":"ApGeo", "volume_begin":1, "volume_end":169},
            {"journal":"APhy", "volume_begin":1, "volume_end":169},{"journal":"ApJ", "volume_begin":1, "volume_end":473},
            {"journal":"ApJS", "volume_begin":1, "volume_end":107},{"journal":"ApNan", "volume_begin":1, "volume_end":169},
            {"journal":"ApNr", "all_volume":True},{"journal":"ApPhA", "volume_begin":1, "volume_end":169},
            {"journal":"ApPhB", "volume_begin":1, "volume_end":169},{"journal":"ApPhy", "volume_begin":1, "volume_end":169},
            {"journal":"ApWS", "volume_begin":1, "volume_end":169},{"journal":"ARA&A", "all_volume":True},
            {"journal":"ARep", "volume_begin":1, "volume_end":169},{"journal":"AREPS", "volume_begin":1, "volume_end":23},
            {"journal":"ARIJ", "volume_begin":1, "volume_end":169},{"journal":"ArM", "volume_begin":1, "volume_end":169},
            {"journal":"ArRMA", "volume_begin":1, "volume_end":169},{"journal":"AsDyn", "volume_begin":1, "volume_end":169},
            {"journal":"ASPC", "volume_begin":1, "volume_end":261},{"journal":"ASPC", "volume_number":305},
            {"journal":"ASPC", "volume_number":308},  {"journal":"ASPC", "volume_number":314},
            {"journal":"AstBu", "volume_begin":1, "volume_end":169},{"journal":"AstL", "volume_begin":1, "volume_end":169},
            {"journal":"AtOO", "volume_begin":1, "volume_end":169},{"journal":"BaltA", "all_volume":True},
            {"journal":"BASI", "volume_begin":1, "volume_end":34},{"journal":"BeiMP", "volume_begin":1, "volume_end":169},
            {"journal":"BGeod", "volume_begin":1, "volume_end":169},{"journal":"BoLMe", "volume_begin":1, "volume_end":169},
            {"journal":"BRASP", "volume_begin":1, "volume_end":169},{"journal":"BrJPh", "volume_begin":1, "volume_end":169},
            {"journal":"BuLPI", "volume_begin":1, "volume_end":169},{"journal":"BVol", "volume_begin":1, "volume_end":169},
            {"journal":"CEAS", "volume_begin":1, "volume_end":169},{"journal":"CEJE", "volume_begin":1, "volume_end":169},
            {"journal":"CEJG", "volume_begin":1, "volume_end":169},{"journal":"CEJPh", "volume_begin":1, "volume_end":169},
            {"journal":"CeMDA", "volume_begin":46, "volume_end":66},{"journal":"CeMec", "all_volume":True},
            {"journal":"CESW", "volume_begin":1, "volume_end":169},{"journal":"ChJOL", "volume_begin":1, "volume_end":169},
            {"journal":"ClDy", "volume_begin":1, "volume_end":169},{"journal":"CMaPh", "volume_begin":1, "volume_end":169},
            {"journal":"CMMPh", "volume_begin":1, "volume_end":169},{"journal":"CmPhy", "volume_begin":1, "volume_end":169},
            {"journal":"CMT", "volume_begin":1, "volume_end":169},{"journal":"CoAst", "volume_begin":1, "volume_end":150},
            {"journal":"ComAC", "volume_begin":1, "volume_end":169},{"journal":"CoMP", "volume_begin":1, "volume_end":169},
            {"journal":"CompM", "volume_begin":1, "volume_end":169},{"journal":"CONF", "partial_bibcode":"1999sf99.proc"},
            {"journal":"CorRe", "volume_begin":1, "volume_end":169},{"journal":"CoSka", "volume_begin":1, "volume_end":28},
            {"journal":"CosRe", "volume_begin":1, "volume_end":169},{"journal":"CPM", "volume_begin":1, "volume_end":169},
            {"journal":"CryRp", "volume_begin":1, "volume_end":169},{"journal":"CzJPh", "volume_begin":1, "volume_end":169},
            {"journal":"CzJPS", "volume_begin":1, "volume_end":169},{"journal":"DeHyZ", "volume_begin":1, "volume_end":169},
            {"journal":"DokES", "volume_begin":1, "volume_end":169},{"journal":"DokPh", "volume_begin":1, "volume_end":169},
            {"journal":"EaSci", "volume_begin":1, "volume_end":169},{"journal":"EEEV", "volume_begin":1, "volume_end":169},
            {"journal":"EES", "volume_begin":1, "volume_end":169},{"journal":"EFM", "volume_begin":1, "volume_end":169},
            {"journal":"EJASP", "volume_begin":1, "volume_end":169},{"journal":"EM&P", "volume_begin":1, "volume_end":169},
            {"journal":"EM+P", "volume_begin":30, "volume_end":63},{"journal":"EML", "volume_begin":1, "volume_end":169},
            {"journal":"EnGeo", "volume_begin":1, "volume_end":169},{"journal":"EnMan", "volume_begin":1, "volume_end":169},
            {"journal":"EP+S", "volume_begin":1, "volume_end":169},{"journal":"EPJA", "volume_begin":1, "volume_end":169},
            {"journal":"EPJAS", "volume_begin":1, "volume_end":169},{"journal":"EPJB", "volume_begin":1, "volume_end":169},
            {"journal":"EPJC", "volume_begin":1, "volume_end":169},{"journal":"EPJCS", "volume_begin":1, "volume_end":169},
            {"journal":"EPJD", "volume_begin":1, "volume_end":169},{"journal":"EPJH", "volume_begin":1, "volume_end":169},
            {"journal":"EPJP", "volume_begin":1, "volume_end":169},{"journal":"EPJQT", "volume_begin":1, "volume_end":169},
            {"journal":"ESE", "volume_begin":1, "volume_end":169},{"journal":"EurSS", "volume_begin":1, "volume_end":169},
            {"journal":"ExA", "volume_begin":1, "volume_end":169},{"journal":"ExFl", "volume_begin":1, "volume_end":169},
            {"journal":"FBS", "volume_begin":1, "volume_end":169},{"journal":"FoPh", "volume_begin":1, "volume_end":169},
            {"journal":"FoPhL", "volume_begin":1, "volume_end":169},{"journal":"FPhL", "volume_begin":1, "volume_end":169},
            {"journal":"FrME", "volume_begin":1, "volume_end":169},{"journal":"FrMS", "volume_begin":1, "volume_end":169},
            {"journal":"FrPhC", "volume_begin":1, "volume_end":169},{"journal":"FrPhy", "volume_begin":1, "volume_end":169},
            {"journal":"FTC", "volume_begin":1, "volume_end":169},{"journal":"Ge&Ae", "volume_begin":1, "volume_end":169},
            {"journal":"Ge+Ae", "volume_begin":1, "volume_end":169},{"journal":"GeoOD", "volume_begin":1, "volume_end":169},
            {"journal":"GeoPA", "volume_begin":1, "volume_end":169},{"journal":"GeoRU", "volume_begin":1, "volume_end":169},
            {"journal":"GeoSu", "volume_begin":1, "volume_end":169},{"journal":"Geote", "volume_begin":1, "volume_end":169},
            {"journal":"GML", "volume_begin":1, "volume_end":169},{"journal":"GrCo", "volume_begin":1, "volume_end":169},
            {"journal":"GReGr", "volume_begin":1, "volume_end":169},{"journal":"Grund", "volume_begin":1, "volume_end":169},
            {"journal":"GSL", "volume_begin":1, "volume_end":169},{"journal":"HiA", "volume_begin":13, "volume_end":14},
            {"journal":"HM", "volume_begin":1, "volume_end":169},{"journal":"HMR", "volume_begin":1, "volume_end":169},
            {"journal":"HMT", "volume_begin":1, "volume_end":169},{"journal":"HWM", "volume_begin":1, "volume_end":169},
            {"journal":"HydJ", "volume_begin":1, "volume_end":169},{"journal":"HyInt", "volume_begin":1, "volume_end":169},
            {"journal":"IAM", "volume_begin":1, "volume_end":169},{"journal":"IAUS", "volume_begin":1, "volume_end":234},
            {"journal":"IJASE", "volume_begin":1, "volume_end":169},{"journal":"IJBB", "volume_begin":1, "volume_end":169},
            {"journal":"IJBm", "volume_begin":1, "volume_end":169},{"journal":"IJEaS", "volume_begin":1, "volume_end":169},
            {"journal":"IJEnR", "volume_begin":1, "volume_end":169},{"journal":"IJIMW", "volume_begin":1, "volume_end":169},
            {"journal":"IJMMD", "volume_begin":1, "volume_end":169},{"journal":"IJMW", "volume_begin":1, "volume_end":169},
            {"journal":"IJT", "volume_begin":1, "volume_end":169},{"journal":"IJTP", "volume_begin":1, "volume_end":169},
            {"journal":"InJPh", "volume_begin":1, "volume_end":169},{"journal":"INL", "volume_begin":1, "volume_end":169},
            {"journal":"IREdu", "volume_begin":1, "volume_end":169},{"journal":"IzAOP", "volume_begin":1, "volume_end":169},
            {"journal":"IzPSE", "volume_begin":1, "volume_end":169},{"journal":"JAMTP", "volume_begin":1, "volume_end":169},
            {"journal":"JApSp", "volume_begin":1, "volume_end":169},{"journal":"JASMS", "volume_begin":1, "volume_end":169},
            {"journal":"JCAMD", "volume_begin":1, "volume_end":169},{"journal":"JDBM", "volume_begin":1, "volume_end":169},
            {"journal":"JEET", "volume_begin":1, "volume_end":169},{"journal":"JEMat", "volume_begin":1, "volume_end":169},
            {"journal":"JEOS", "volume_begin":1, "volume_end":169},{"journal":"JEP", "volume_begin":1, "volume_end":169},
            {"journal":"JEPT", "volume_begin":1, "volume_end":169},{"journal":"JESS", "volume_begin":1, "volume_end":169},
            {"journal":"JETP", "volume_begin":1, "volume_end":169},{"journal":"JETPfoo", "volume_begin":1, "volume_end":169},
            {"journal":"JETPL", "volume_begin":1, "volume_end":169},{"journal":"JGeod", "volume_begin":1, "volume_end":169},
            {"journal":"JGS", "volume_begin":1, "volume_end":169},{"journal":"JIEI", "volume_begin":1, "volume_end":169},
            {"journal":"JIEIA", "volume_begin":1, "volume_end":169},{"journal":"JIEIB", "volume_begin":1, "volume_end":169},
            {"journal":"JIEIC", "volume_begin":1, "volume_end":169},{"journal":"JIEID", "volume_begin":1, "volume_end":169},
            {"journal":"JIEIE", "volume_begin":1, "volume_end":169},{"journal":"JIEIn", "volume_begin":1, "volume_end":169},
            {"journal":"JIMTW", "volume_begin":1, "volume_end":169},{"journal":"JKPS", "volume_begin":1, "volume_end":169},
            {"journal":"JLT", "volume_begin":1, "volume_end":169},{"journal":"JLTP", "volume_begin":1, "volume_end":169},
            {"journal":"JMarA", "volume_begin":1, "volume_end":169},{"journal":"JMEP", "volume_begin":1, "volume_end":169},
            {"journal":"JMFM", "volume_begin":1, "volume_end":169},{"journal":"JMSA", "volume_begin":1, "volume_end":169},
            {"journal":"JNR", "volume_begin":1, "volume_end":169},{"journal":"JNS", "volume_begin":1, "volume_end":169},
            {"journal":"JOM", "volume_begin":1, "volume_end":169},{"journal":"JOUC", "volume_begin":1, "volume_end":169},
            {"journal":"JPalA", "volume_begin":1, "volume_end":169},{"journal":"JPalg", "volume_begin":1, "volume_end":169},
            {"journal":"JPRSG", "volume_begin":1, "volume_end":169},{"journal":"JRASC", "volume_begin":1, "volume_end":100},
            {"journal":"JSEdT", "volume_begin":1, "volume_end":169},{"journal":"JSeis", "volume_begin":1, "volume_end":169},
            {"journal":"JSER", "volume_begin":1, "volume_end":169},{"journal":"JSP", "volume_begin":1, "volume_end":169},
            {"journal":"JSTEd", "volume_begin":1, "volume_end":169},{"journal":"JTAP", "volume_begin":1, "volume_end":169},
            {"journal":"JTePh", "volume_begin":1, "volume_end":169},{"journal":"JThSc", "volume_begin":1, "volume_end":169},
            {"journal":"JTST", "volume_begin":1, "volume_end":169},{"journal":"LaPhy", "volume_begin":1, "volume_end":169},
            {"journal":"LMaPh", "volume_begin":1, "volume_end":169},{"journal":"LMMP", "volume_begin":1, "volume_end":169},
            {"journal":"LowOB", "all_volume":True},{"journal":"LPI", "volume_begin":1, "volume_end":27},
            {"journal":"LPSC", "all_volume":True},{"journal":"LRCA", "volume_begin":1, "volume_end":169},
            {"journal":"M+P", "all_volume":True},{"journal":"MAMMP", "volume_begin":1, "volume_end":169},
            {"journal":"MAP", "volume_begin":1, "volume_end":169},{"journal":"MarGR", "volume_begin":1, "volume_end":169},
            {"journal":"MatTh", "volume_begin":1, "volume_end":169},{"journal":"MCM", "volume_begin":1, "volume_end":169},
            {"journal":"MecSM", "volume_begin":1, "volume_end":169},{"journal":"MEdRJ", "volume_begin":1, "volume_end":169},
            {"journal":"MeSol", "volume_begin":1, "volume_end":169},{"journal":"MicNa", "volume_begin":1, "volume_end":169},
            {"journal":"MicST", "volume_begin":1, "volume_end":169},{"journal":"MinDe", "volume_begin":1, "volume_end":169},
            {"journal":"MinPe", "volume_begin":1, "volume_end":169},{"journal":"MMA", "volume_begin":1, "volume_end":169},
            {"journal":"MMI", "volume_begin":1, "volume_end":169},{"journal":"MmRAS", "volume_begin":1, "volume_end":85},
            {"journal":"MMTA", "volume_begin":1, "volume_end":169},{"journal":"MMTB", "volume_begin":1, "volume_end":169},
            {"journal":"MNRAS", "volume_begin":1, "volume_end":301},{"journal":"MNSL", "volume_begin":1, "volume_end":169},
            {"journal":"Moon", "all_volume":True},{"journal":"MPAG", "volume_begin":1, "volume_end":169},
            {"journal":"MSE", "volume_begin":1, "volume_end":169},{"journal":"MSHT", "volume_begin":1, "volume_end":169},
            {"journal":"MT", "volume_begin":1, "volume_end":169},{"journal":"MTA", "volume_begin":1, "volume_end":169},
            {"journal":"MTB", "volume_begin":1, "volume_end":169},{"journal":"MTDM", "volume_begin":1, "volume_end":169},
            {"journal":"MUPB", "volume_begin":1, "volume_end":169},{"journal":"MWE", "volume_begin":1, "volume_end":169},
            {"journal":"NanMe", "volume_begin":1, "volume_end":169},{"journal":"NanoC", "volume_begin":1, "volume_end":169},
            {"journal":"NatAs", "volume_begin":1, "volume_end":169},{"journal":"NatCC", "volume_begin":1, "volume_end":169},
            {"journal":"NatCo", "volume_begin":1, "volume_end":169},{"journal":"NatEn", "volume_begin":1, "volume_end":169},
            {"journal":"NatGe", "volume_begin":1, "volume_end":169},{"journal":"NatRM", "volume_begin":1, "volume_end":169},
            {"journal":"NatSD", "volume_begin":1, "volume_end":169},{"journal":"NatSR", "volume_begin":1, "volume_end":169},
            {"journal":"NML", "volume_begin":1, "volume_end":169},{"journal":"npjAM", "volume_begin":1, "volume_end":169},
            {"journal":"npjCA", "volume_begin":1, "volume_end":169},{"journal":"npjCM", "volume_begin":1, "volume_end":169},
            {"journal":"npjQI", "volume_begin":1, "volume_end":169},{"journal":"npjQM", "volume_begin":1, "volume_end":169},
            {"journal":"npjRM", "volume_begin":1, "volume_end":169},{"journal":"npjSL", "volume_begin":1, "volume_end":169},
            {"journal":"NRL", "volume_begin":1, "volume_end":169},{"journal":"NW", "volume_begin":1, "volume_end":169},
            {"journal":"OcDyn", "volume_begin":1, "volume_end":169},{"journal":"Ocgy", "volume_begin":1, "volume_end":169},
            {"journal":"OERv", "volume_begin":1, "volume_end":169},{"journal":"OIDP", "volume_begin":1, "volume_end":169},
            {"journal":"OLEB", "volume_begin":1, "volume_end":169},{"journal":"OptEL", "volume_begin":1, "volume_end":169},
            {"journal":"OptNa", "volume_begin":1, "volume_end":169},{"journal":"OptRv", "volume_begin":1, "volume_end":169},
            {"journal":"OptSp", "volume_begin":1, "volume_end":169},{"journal":"OQEle", "volume_begin":1, "volume_end":169},
            {"journal":"OrLi", "volume_begin":1, "volume_end":169},{"journal":"OSJ", "volume_begin":1, "volume_end":169},
            {"journal":"PAN", "volume_begin":1, "volume_end":169},{"journal":"PApGe", "volume_begin":1, "volume_end":169},
            {"journal":"PASJ", "volume_begin":1, "volume_end":50},{"journal":"PASP", "volume_begin":1, "volume_end":109},
            {"journal":"PCM", "volume_begin":1, "volume_end":169},{"journal":"PCMPS", "volume_begin":1, "volume_end":169},
            {"journal":"PEPS", "volume_begin":1, "volume_end":169},{"journal":"PESS", "volume_begin":1, "volume_end":169},
            {"journal":"PFG", "volume_begin":1, "volume_end":169},{"journal":"PhP", "volume_begin":1, "volume_end":169},
            {"journal":"PhSen", "volume_begin":1, "volume_end":169},{"journal":"PhSS", "volume_begin":1, "volume_end":169},
            {"journal":"PhyMe", "volume_begin":1, "volume_end":169},{"journal":"PKM", "volume_begin":1, "volume_end":169},
            {"journal":"PlPhR", "volume_begin":1, "volume_end":169},{"journal":"PlSci", "volume_begin":1, "volume_end":169},
            {"journal":"PMM", "volume_begin":1, "volume_end":169},{"journal":"Polyt", "volume_begin":1, "volume_end":169},
            {"journal":"PPN", "volume_begin":1, "volume_end":169},{"journal":"PPNL", "volume_begin":1, "volume_end":169},
            {"journal":"Prama", "volume_begin":1, "volume_end":169},{"journal":"PWP", "volume_begin":1, "volume_end":169},
            {"journal":"QuIP", "volume_begin":1, "volume_end":169},{"journal":"R&QE", "volume_begin":1, "volume_end":169},
            {"journal":"R+QE", "volume_begin":1, "volume_end":169},{"journal":"RaF", "volume_begin":1, "volume_end":169},
            {"journal":"RCD", "volume_begin":1, "volume_end":169},{"journal":"RDTM", "volume_begin":1, "volume_end":169},
            {"journal":"RJMP", "volume_begin":1, "volume_end":169},{"journal":"RJPCA", "volume_begin":1, "volume_end":169},
            {"journal":"RMFMR", "volume_begin":1, "volume_end":169},{"journal":"RMRE", "volume_begin":1, "volume_end":169},
            {"journal":"RMxAA", "volume_begin":1, "volume_end":35},{"journal":"RScEd", "volume_begin":1, "volume_end":169},
            {"journal":"RSESS", "volume_begin":1, "volume_end":169},{"journal":"RuAer", "volume_begin":1, "volume_end":169},
            {"journal":"RuJPC", "volume_begin":1, "volume_end":169},{"journal":"RuMet", "volume_begin":1, "volume_end":169},
            {"journal":"RuPhJ", "volume_begin":1, "volume_end":169},{"journal":"RvMA", "all_volume":True},
            {"journal":"RvMPP", "volume_begin":1, "volume_end":169},{"journal":"Sc&Ed", "volume_begin":1, "volume_end":169},
            {"journal":"Sc+Ed", "volume_begin":1, "volume_end":169},{"journal":"ScChG", "volume_begin":1, "volume_end":169},
            {"journal":"SciNa", "volume_begin":1, "volume_end":169},{"journal":"SCPMA", "volume_begin":1, "volume_end":169},
            {"journal":"SenIm", "volume_begin":1, "volume_end":169},{"journal":"SGC", "volume_begin":1, "volume_end":169},
            {"journal":"SGeo", "volume_begin":1, "volume_end":169},{"journal":"SHH", "volume_begin":1, "volume_end":169},
            {"journal":"ShMeS", "volume_begin":1, "volume_end":169},{"journal":"ShWav", "volume_begin":1, "volume_end":169},
            {"journal":"SLSci", "volume_begin":1, "volume_end":169},{"journal":"SMS", "volume_begin":1, "volume_end":169},
            {"journal":"SoPh", "volume_begin":1, "volume_end":169},{"journal":"SoSyR", "volume_begin":1, "volume_end":169},
            {"journal":"SPRINGER", "volume_begin":1, "volume_end":169},{"journal":"SSRv", "volume_begin":1, "volume_end":169},
            {"journal":"StMat", "volume_begin":1, "volume_end":169},{"journal":"SuEa", "volume_begin":1, "volume_end":169},
            {"journal":"SvA", "volume_begin":1, "volume_end":37},{"journal":"SvAL",  "all_volume":True},
            {"journal":"SvApM", "volume_begin":1, "volume_end":169},{"journal":"SvRP", "volume_begin":1, "volume_end":169},
            {"journal":"TDR", "volume_begin":1, "volume_end":169},{"journal":"TePhL", "volume_begin":1, "volume_end":169},
            {"journal":"Th&Ae", "volume_begin":1, "volume_end":169},{"journal":"Th+Ae", "volume_begin":1, "volume_end":169},
            {"journal":"ThApC", "volume_begin":1, "volume_end":169},{"journal":"ThCFD", "volume_begin":1, "volume_end":169},
            {"journal":"ThEng", "volume_begin":1, "volume_end":169},{"journal":"TMP", "volume_begin":1, "volume_end":169},
            {"journal":"W+S", "volume_begin":1, "volume_end":169},{"journal":"ZAGeo", "volume_begin":1, "volume_end":169},
            {"journal":"ZaMP", "volume_begin":1, "volume_end":169},{"journal":"ZFHDG", "volume_begin":1, "volume_end":169},
            {"journal":"ZPhy", "volume_begin":1, "volume_end":169},{"journal":"ZPhyA", "volume_begin":1, "volume_end":169},
            {"journal":"ZPhyB", "volume_begin":1, "volume_end":169},{"journal":"ZPhyC", "volume_begin":1, "volume_end":169},
            {"journal":"ZPhyD", "volume_begin":1, "volume_end":169},
        ]},
        {'name': 'ADStex', 'extension_pattern': '.raw', 'reference_service_endpoint': '/text', 'matches': [
            {"journal":"A+AS", "all_volume":True},{"journal":"ASPC", "all_volume":True},
            {"journal":"BAAA", "all_volume":True},{"journal":"BASI", "all_volume":True},
            {"journal":"BlgAJ", "all_volume":True},{"journal":"CoKon", "all_volume":True},
            {"journal":"CONF", "partial_bibcode":"1977egsp.conf"},{"journal":"CONF", "partial_bibcode":"1979pimo.conf"},
            {"journal":"CONF", "partial_bibcode":"1981seng.proc"},{"journal":"CONF", "partial_bibcode":"1987pimo.conf"},
            {"journal":"CONF", "partial_bibcode":"1990pimo.conf"},{"journal":"CONF", "partial_bibcode":"1991pimo.conf"},
            {"journal":"CONF", "partial_bibcode":"1992daec.conf"},{"journal":"CONF", "partial_bibcode":"1993pimo.conf"},
            {"journal":"CONF", "partial_bibcode":"1996psrd.rept"},{"journal":"CONF", "partial_bibcode":"1997IAUS..182"},
            {"journal":"CONF", "partial_bibcode":"1997psrd.rept"},{"journal":"CONF", "partial_bibcode":"1997scor.proc"},
            {"journal":"CONF", "partial_bibcode":"1998dggn.conf"},{"journal":"CONF", "partial_bibcode":"1998pimo.conf"},
            {"journal":"CONF", "partial_bibcode":"1998psrd.rept"},{"journal":"CONF", "partial_bibcode":"1999asdi.conf"},
            {"journal":"CONF", "partial_bibcode":"1999cezh.conf"},{"journal":"CONF", "partial_bibcode":"1999cpg..conf"},
            {"journal":"CONF", "partial_bibcode":"1999gady.conf"},{"journal":"CONF", "partial_bibcode":"1999ldss.work"},
            {"journal":"CONF", "partial_bibcode":"1999obco.conf"},{"journal":"CONF", "partial_bibcode":"1999pimo.conf"},
            {"journal":"CONF", "partial_bibcode":"1999psrd.rept"},{"journal":"CONF", "partial_bibcode":"2000cosm.conf"},
            {"journal":"CONF", "partial_bibcode":"2000dgeu.conf"},{"journal":"CONF", "partial_bibcode":"2000fepc.conf"},
            {"journal":"CONF", "partial_bibcode":"2000fist.conf"},{"journal":"CONF", "partial_bibcode":"2000ltse.conf"},
            {"journal":"CONF", "partial_bibcode":"2000pimo.conf"},{"journal":"CONF", "partial_bibcode":"2000psrd.rept"},
            {"journal":"CONF", "partial_bibcode":"2000sgg..conf"},{"journal":"CONF", "partial_bibcode":"2000tesa.conf"},
            {"journal":"CONF", "partial_bibcode":"2001aocd.book"},{"journal":"CONF", "partial_bibcode":"2001bhbg.conf"},
            {"journal":"CONF", "partial_bibcode":"2002pcvr.conf"},{"journal":"CONF", "partial_bibcode":"2003IAUS..212"},
            {"journal":"CONF", "partial_bibcode":"2003lisa.conf"},{"journal":"CONF", "partial_bibcode":"2004rcfg.proc"},
            {"journal":"CONF", "partial_bibcode":"2006mha..book"},{"journal":"CONF", "partial_bibcode":"2008hsf1.book"},
            {"journal":"CONF", "partial_bibcode":"2008hsf2.book"},{"journal":"CONF", "partial_bibcode":"2009nqsa.conf"},
            {"journal":"IBVS", "all_volume":True},  {"journal":"JKAS", "all_volume":True},
            {"journal":"OTHER", "partial_bibcode":"1973PhDT.........8B"},{"journal":"OTHER", "partial_bibcode":"1987PhDT........12N"},
            {"journal":"OTHER", "partial_bibcode":"1996PhDT........59R"},{"journal":"OTHER", "partial_bibcode":"1996PhDT........97K"},
            {"journal":"OTHER", "partial_bibcode":"2000PhDT.......127T"},{"journal":"OTHER", "partial_bibcode":"2001PhDT.........5B"},
            {"journal":"OTHER", "partial_bibcode":"2006PhDT.........6G"},{"journal":"OTHER", "partial_bibcode":"2006PhDT.........7B"},
            {"journal":"OTHER", "partial_bibcode":"2009arXiv0901.0868D"},{"journal":"OTHER", "partial_bibcode":"2009MsT..........1D"},
            {"journal":"OTHER", "partial_bibcode":"2011PhDT.......210W"},{"journal":"OTHER", "partial_bibcode":"2011PhDT.......303C"},
            {"journal":"OTHER", "partial_bibcode":"2013PhDT.......126G"},{"journal":"OTHER", "partial_bibcode":"2014PhDT........76D"},
            {"journal":"OTHER", "partial_bibcode":"2014PhDT.......594S"},{"journal":"OTHER", "partial_bibcode":"2015PhDT.......101L"},
            {"journal":"OTHER", "partial_bibcode":"2015pta..conf"},  {"journal":"OTHER", "partial_bibcode":"2015tyge.conf"},
            {"journal":"OTHER", "partial_bibcode":"2016arXiv160104346L"},{"journal":"OTHER", "partial_bibcode":"2016arXiv160208065M"},
            {"journal":"OTHER", "partial_bibcode":"2016arXiv160401122A"},{"journal":"OTHER", "partial_bibcode":"2016IASP....1.....R"},
            {"journal":"OTHER", "partial_bibcode":"2016IFASP...1.....R"},{"journal":"OTHER", "partial_bibcode":"2016PhDT.......239R"},
            {"journal":"OTHER", "partial_bibcode":"2017arXiv170304540M"},{"journal":"OTHER", "partial_bibcode":"2017arXiv170702986G"},
            {"journal":"OTHER", "partial_bibcode":"2017PhDT........33O"},{"journal":"OTHER", "partial_bibcode":"2018arXiv180104370T"},
            {"journal":"OTHER", "partial_bibcode":"2018arXiv180104371S"},{"journal":"OTHER", "partial_bibcode":"2018arXiv181203686P"},
            {"journal":"OTHER", "partial_bibcode":"2018exha.book.....P"},{"journal":"OTHER", "partial_bibcode":"2019arXiv190304324K"},
            {"journal":"OTHER", "partial_bibcode":"2019arXiv190304424A"},{"journal":"OTHER", "partial_bibcode":"2019arXiv191102859B"},
            {"journal":"OTHER", "partial_bibcode":"2021arXiv210103670A"},{"journal":"OTHER", "partial_bibcode":"2021arXiv210205064F"},
            {"journal":"OTHER", "partial_bibcode":"asd..soft"},  {"journal":"PAICz", "all_volume":True},
        ]},
        {'name': 'AnAtexE2', 'extension_pattern': '.tex', 'reference_service_endpoint': '/text', 'matches': [
            {"journal":"A+A", "volume_begin":372, "volume_end":429},{"journal":"AN", "volume_number":237},
            {"journal":"AN", "volume_begin":322, "volume_end":999},{"journal":"BaltA", "all_volume": True},
            {"journal":"MmSAI", "all_volume": True},{"journal":"MSAIS", "all_volume": True},
            {"journal":"PASA", "volume_begin":18, "volume_end":19},

        ]},
        {'name': 'ADStexE3', 'extension_pattern': '.refs', 'reference_service_endpoint': '/text', 'matches': [
            {"journal": "OTHER", "partial_bibcode":"2011piim.book.....D"},
        ]},
        {'name': 'ADStexE4', 'extension_pattern': '.new', 'reference_service_endpoint': '/text', 'matches': [
            {"journal":"CONF", "partial_bibcode":"2004oee..symp"},{"journal":"CONF", "partial_bibcode":"2004mmu..symp"},
            {"journal":"CONF", "partial_bibcode":"2004cgpc.symp"},{"journal":"CONF", "partial_bibcode":"2004cbhg.symp"},
        ]},
        {'name': 'ADStxt', 'extension_pattern': '.raw', 'reference_service_endpoint': '/text', 'matches': [
            {"journal":"A+ARv", "volume_begin":1996, "volume_end":2004},{"journal":"A+AT", "all_volume":True},
            {"journal":"AANv", "all_volume":True},{"journal":"AASP", "all_volume":True},
            {"journal":"AcA", "volume_begin":49, "volume_end":58},{"journal":"AcASn", "all_volume":True},
            {"journal":"Apei", "all_volume":True},{"journal":"ARI", "all_volume":True},
            {"journal":"ASD", "all_volume":True},{"journal":"ASInC", "all_volume":True},
            {"journal":"BlAJ", "all_volume":True},{"journal":"BOTT", "all_volume":True},
            {"journal":"BSRSL", "all_volume":True},  {"journal":"CoAst", "all_volume":True},
            {"journal":"CONF", "partial_bibcode":"2001cksa.conf"},{"journal":"CONF", "partial_bibcode":"2001defi.conf"},
            {"journal":"CONF", "partial_bibcode":"2001gge..conf"},{"journal":"CONF", "partial_bibcode":"2000prpl.conf"},
            {"journal":"CONF", "partial_bibcode":"2001IAUS..200"},{"journal":"CONF", "partial_bibcode":"2001pao..conf"},
            {"journal":"CONF", "partial_bibcode":"2001pimo.conf"},{"journal":"CONF", "partial_bibcode":"2001psrd.rept"},
            {"journal":"CONF", "partial_bibcode":"2001qarr.conf"},{"journal":"CONF", "partial_bibcode":"2001ragt.meet"},
            {"journal":"CONF", "partial_bibcode":"2002adass..11"},{"journal":"CONF", "partial_bibcode":"2002dgkd.conf"},
            {"journal":"CONF", "partial_bibcode":"2002evn..conf"},{"journal":"CONF", "partial_bibcode":"2002IAUS..207"},
            {"journal":"CONF", "partial_bibcode":"2002luml.conf"},{"journal":"CONF", "partial_bibcode":"2002nla..work"},
            {"journal":"CONF", "partial_bibcode":"2002osp..conf"},{"journal":"CONF", "partial_bibcode":"2002psrd.rept"},
            {"journal":"CONF", "partial_bibcode":"2002sdef.conf"},{"journal":"CONF", "partial_bibcode":"2003acfp.conf"},
            {"journal":"CONF", "partial_bibcode":"2003adass..12"},{"journal":"CONF", "partial_bibcode":"2003csss...12"},
            {"journal":"CONF", "partial_bibcode":"2003egcs.conf"},{"journal":"CONF", "partial_bibcode":"2003fthp.conf"},
            {"journal":"CONF", "partial_bibcode":"2003mglh.conf"},{"journal":"CONF", "partial_bibcode":"2003mpse.conf"},
            {"journal":"CONF", "partial_bibcode":"2003psrd.rept"},{"journal":"CONF", "partial_bibcode":"2003tdse.conf"},
            {"journal":"CONF", "partial_bibcode":"2003trt..work"},{"journal":"CONF", "partial_bibcode":"2003whdw.conf"},
            {"journal":"CONF", "partial_bibcode":"2004bdmh.conf"},{"journal":"CONF", "partial_bibcode":"2004mast.conf"},
            {"journal":"CONF", "partial_bibcode":"2004otp..work"},{"journal":"CONF", "partial_bibcode":"2004psrd.rept"},
            {"journal":"CONF", "partial_bibcode":"2004sdab.conf"},{"journal":"CONF", "partial_bibcode":"2004ssrc.conf"},
            {"journal":"CONF", "partial_bibcode":"2004tivo.conf"},{"journal":"CONF", "partial_bibcode":"2005AIPC..761"},
            {"journal":"CONF", "partial_bibcode":"2005daas.conf"},{"journal":"CONF", "partial_bibcode":"2005prpl.conf"},
            {"journal":"CONF", "partial_bibcode":"2005psrd.rept"},{"journal":"CONF", "partial_bibcode":"2005ragt.meet"},
            {"journal":"CONF", "partial_bibcode":"2005smp..conf"},{"journal":"CONF", "partial_bibcode":"2005vopc.conf"},
            {"journal":"CONF", "partial_bibcode":"2005yosc.conf"},{"journal":"CONF", "partial_bibcode":"2006amos.conf"},
            {"journal":"CONF", "partial_bibcode":"2006nla..conf"},{"journal":"CONF", "partial_bibcode":"2006psrd.rept"},
            {"journal":"CONF", "partial_bibcode":"2006tafp.conf"},{"journal":"CONF", "partial_bibcode":"2006yosc.conf"},
            {"journal":"CONF", "partial_bibcode":"2007amos.conf"},{"journal":"CONF", "partial_bibcode":"2007msfa.conf"},
            {"journal":"CONF", "partial_bibcode":"2007pms..conf"},{"journal":"CONF", "partial_bibcode":"2007psrd.rept"},
            {"journal":"CONF", "partial_bibcode":"2007ragt.meet"},{"journal":"CONF", "partial_bibcode":"2007soch.conf"},
            {"journal":"CONF", "partial_bibcode":"2007waas.work"},{"journal":"CONF", "partial_bibcode":"2008ysc..conf"},
            {"journal":"CONF", "partial_bibcode":"2009eimw.conf"},{"journal":"CONF", "partial_bibcode":"2010pim8.conf"},
            {"journal":"CONF", "partial_bibcode":"2010pim9.conf"},{"journal":"CONF", "partial_bibcode":"2010sf2a.conf"},
            {"journal":"CONF", "partial_bibcode":"2010ttt..work"},{"journal":"CONF", "partial_bibcode":"2011mast.conf"},
            {"journal":"CONF", "partial_bibcode":"2011pimo.conf"},{"journal":"CONF", "partial_bibcode":"2011sf2a.conf"},
            {"journal":"CONF", "partial_bibcode":"2011tfa..conf"},{"journal":"CONF", "partial_bibcode":"2012pimo.conf"},
            {"journal":"CONF", "partial_bibcode":"2012sf2a.conf"},{"journal":"CONF", "partial_bibcode":"2013pimo.conf"},
            {"journal":"CONF", "partial_bibcode":"2014apn6.conf"},
            {"journal":"CoSka", "all_volume":True},{"journal":"EJTP", "all_volume":True},
            {"journal":"eMetN", "all_volume":True},{"journal":"ErNW", "all_volume":True},
            {"journal":"GeIss", "all_volume":True},  {"journal":"IAUIn", "all_volume":True},
            {"journal":"ISSIR", "all_volume":True},  {"journal":"JAD", "all_volume":True},
            {"journal":"JApA", "all_volume":True},  {"journal":"JASS", "all_volume":True},
            {"journal":"JAVSO", "all_volume":True},{"journal":"JIMO", "all_volume":True},
            {"journal":"JIntS", "all_volume":True},  {"journal":"JSARA", "all_volume":True},
            {"journal":"KFNT", "all_volume":True},  {"journal":"Level5", "all_volume":True},
            {"journal":"LPI", "all_volume":True},{"journal":"LRR", "all_volume":True},
            {"journal":"LRSP", "all_volume":True},{"journal":"MAA", "all_volume":True},
            {"journal":"Msngr", "all_volume":True},  {"journal":"OTHER", "partial_bibcode":"1964MSRSL..26..476K"},
            {"journal":"OTHER", "partial_bibcode":"1983ASPRv...2..189P"},{"journal":"OTHER", "partial_bibcode":"1992cdtp.book..161T"},
            {"journal":"OTHER", "partial_bibcode":"1992CoSys...6..137T"},{"journal":"OTHER", "partial_bibcode":"1992qcqm.book..187T"},
            {"journal":"OTHER", "partial_bibcode":"1994dcgr.book..251T"},{"journal":"OTHER", "partial_bibcode":"1994fnas.book..431T"},
            {"journal":"OTHER", "partial_bibcode":"1995dsc..cof..324T"},{"journal":"OTHER", "partial_bibcode":"1995dsc..conf..324T"},
            {"journal":"OTHER", "partial_bibcode":"1995gtmp.book..479T"},{"journal":"OTHER", "partial_bibcode":"1996vbps.conf...21E"},
            {"journal":"OTHER", "partial_bibcode":"1996vbps.conf...23E"},{"journal":"OTHER", "partial_bibcode":"1997gbas.confE...1E"},
            {"journal":"OTHER", "partial_bibcode":"2002AdAMP..48..263F"},{"journal":"OTHER", "partial_bibcode":"2003PhDT.......177P"},
            {"journal":"OTHER", "partial_bibcode":"2004CSF....20..713T"},{"journal":"OTHER", "partial_bibcode":"2005JDDE...17...85V"},
            {"journal":"OTHER", "partial_bibcode":"2006csxs.book..623T"},{"journal":"OTHER", "partial_bibcode":"2006PhDT........15F"},
            {"journal":"OTHER", "partial_bibcode":"2007AIPC..948..357M"},{"journal":"OTHER", "partial_bibcode":"2007ASPC..378..251W"},
            {"journal":"OTHER", "partial_bibcode":"2007ASPC..378..450M"},{"journal":"OTHER", "partial_bibcode":"2007HiA....14...63G"},
            {"journal":"OTHER", "partial_bibcode":"2007NewA...12..479S"},{"journal":"OTHER", "partial_bibcode":"2007PhDT........35H"},
            {"journal":"OTHER", "partial_bibcode":"2008AIPC.1016..383M"},{"journal":"OTHER", "partial_bibcode":"2008CQGra..25d5014P"},
            {"journal":"OTHER", "partial_bibcode":"2008evn..confE..63E"},{"journal":"OTHER", "partial_bibcode":"2008IAUS..251..197M"},
            {"journal":"OTHER", "partial_bibcode":"2008JPCA..112.2339H"},{"journal":"OTHER", "partial_bibcode":"2008PCCP...10.2374H"},
            {"journal":"OTHER", "partial_bibcode":"2009arXiv0909.4971M"},{"journal":"OTHER", "partial_bibcode":"2009arXiv0909.4972M"},
            {"journal":"OTHER", "partial_bibcode":"2009ESAST.257.....P"},{"journal":"OTHER", "partial_bibcode":"2009JQSRT.110..533R"},
            {"journal":"OTHER", "partial_bibcode":"2009PhDT.........1M"},{"journal":"OTHER", "partial_bibcode":"2009sfch.book..459C"},
            {"journal":"OTHER", "partial_bibcode":"2010AdAst2010E..21W"},{"journal":"OTHER", "partial_bibcode":"2010BrJPh..40...38R"},
            {"journal":"OTHER", "partial_bibcode":"2010ChSBu..55.3847W"},{"journal":"OTHER", "partial_bibcode":"2010JVGR..193...82D"},
            {"journal":"OTHER", "partial_bibcode":"2010KPCB...26....1Z"},{"journal":"OTHER", "partial_bibcode":"2010pdac.book..230A"},
            {"journal":"OTHER", "partial_bibcode":"2010Sci...327.1470C"},{"journal":"OTHER", "partial_bibcode":"2011PhDT.........1B"},
            {"journal":"OTHER", "partial_bibcode":"2011PhDT.........1R"},{"journal":"OTHER", "partial_bibcode":"2011PhDT........68T"},
            {"journal":"OTHER", "partial_bibcode":"2011PhDT........85L"},{"journal":"OTHER", "partial_bibcode":"2011PhDT.......324K"},
            {"journal":"OTHER", "partial_bibcode":"2011sf2a.conf"},{"journal":"OTHER", "partial_bibcode":"2011sswh.book...31C"},
            {"journal":"OTHER", "partial_bibcode":"2011wdac.book..117F"},{"journal":"OTHER", "partial_bibcode":"2012amld.book"},
            {"journal":"OTHER", "partial_bibcode":"2012IJFPS..37...47M"},{"journal":"OTHER", "partial_bibcode":"2012IJRSG...1....1T"},
            {"journal":"OTHER", "partial_bibcode":"2013BSRSL..82...33D"},{"journal":"OTHER", "partial_bibcode":"2013IJAP....4b...6R"},
            {"journal":"OTHER", "partial_bibcode":"2013IJAP....4d...8R"},{"journal":"OTHER", "partial_bibcode":"2013PhDT.........2I"},
            {"journal":"OTHER", "partial_bibcode":"2014JApS...41..164R"},{"journal":"OTHER", "partial_bibcode":"2014PhDT.......131M"},
            {"journal":"OTHER", "partial_bibcode":"2014PhDT.......337H"},{"journal":"OTHER", "partial_bibcode":"2015pust.book.....C"},
            {"journal":"OTHER", "partial_bibcode":"2016CoSka..46...15K"},{"journal":"OTHER", "partial_bibcode":"2016ESASP1313.....R"},
            {"journal":"OTHER", "partial_bibcode":"2017pcos.book.....J"},{"journal":"OTHER", "partial_bibcode":"2017PhDT.........2N"},
            {"journal":"OTHER", "volume_string":"AIPC"},{"journal":"OTHER", "volume_string":"ASSL"},
            {"journal":"OTHER", "volume_string":"BUEOP"},  {"journal":"OTHER", "volume_string":"FrP"},
            {"journal":"OTHER", "volume_string":"JHEP"},{"journal":"PASJ", "volume_begin":54, "volume_end":9999},
            {"journal":"PNAS", "all_volume":True},{"journal":"POBeo", "all_volume":True},
            {"journal":"PZP", "all_volume":True},  {"journal":"RMxAA", "all_volume":True},
            {"journal":"RMxAC", "all_volume":True},{"journal":"RoAJ", "all_volume":True},
            {"journal":"SerAJ", "all_volume":True},  {"journal":"SpWea", "all_volume":True},
            {"journal":"SunGe", "all_volume":True},  {"journal":"ZGlGl", "all_volume":True},
        ]},
        {'name': 'ADStxtE2', 'extension_pattern': '.refs', 'reference_service_endpoint': '/text', 'matches': [
            {"journal": "OTHER", "partial_bibcode":"2014A+ARv..22...71S"},{"journal": "OTHER", "partial_bibcode":"2012RSPTA.370.3193D"},
        ]},
        {'name': 'ADStxtE3', 'extension_pattern': '.urls.raw', 'reference_service_endpoint': '/text', 'matches': []},
        {'name': 'ADStxtE4', 'extension_pattern': '.adstagged.raw', 'reference_service_endpoint': '/text', 'matches': []},
        {'name': 'ADStxtE5', 'extension_pattern': '.conf.raw', 'reference_service_endpoint': '/text', 'matches': []},
        {'name': 'AEdRvHTML', 'extension_pattern': '.html', 'reference_service_endpoint': '/text', 'matches': [
            {"journal":"AEdRv", "volume_begin":1, "volume_end":5},
        ]},
        {'name': 'AGU', 'extension_pattern': '.agu.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'AIP', 'extension_pattern': '.aip.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'AIPE2', 'extension_pattern': '.xml', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal": "AIP", "all_volume": True},{"journal": "AIPC", "all_volume": True},
            {"journal": "AmJPh", "all_volume": True},{"journal": "ApPhL", "all_volume": True},
            {"journal": "Chaos", "all_volume": True},{"journal": "JAP", "all_volume": True},
            {"journal": "JChPh", "all_volume": True},{"journal": "JMP", "all_volume": True},
            {"journal": "JMPS", "all_volume": True},{"journal": "JPCRD", "all_volume": True},
            {"journal": "LTP", "all_volume": True},{"journal": "PhFl", "all_volume": True},
            {"journal": "PhPl", "all_volume": True},{"journal": "PhTea", "all_volume": True},
            {"journal": "RScI", "all_volume": True},
        ]},
        {'name': 'AnA', 'extension_pattern': '.xml', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal":"A+A", "all_volume":True},
        ]},
        {'name': 'AnAhtml', 'extension_pattern': '.ref.txt', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal": "A+A", "all_volume": True},
        ]},
        {'name': 'AnAShtml', 'extension_pattern': '.txt', 'reference_service_endpoint': '/text', 'matches': [
            {"journal": "A+AS", "volume_begin": 121, "volume_end": 126},
        ]},
        {'name': 'AnRFMhtml', 'extension_pattern': '.html', 'reference_service_endpoint': '/text', 'matches': [
            {"journal": "AnRFM", "volume_begin": 38, "volume_end": 39},
        ]},
        {'name': 'APS', 'extension_pattern': '.aps.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'APSE2', 'extension_pattern': '.ref.xml', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal": "APS", "all_volume": True},{"journal": "PRSTP", "all_volume": True},
            {"journal": "PhRv", "all_volume": True},{"journal": "PhRvA", "all_volume": True},
            {"journal": "PhRvB", "all_volume": True},{"journal": "PhRvC", "all_volume": True},
            {"journal": "PhRvD", "all_volume": True},{"journal": "PhRvE", "all_volume": True},
            {"journal": "PhRvF", "all_volume": True},{"journal": "PhRvI", "all_volume": True},
            {"journal": "PhRvL", "all_volume": True},{"journal": "PhRvS", "all_volume": True},
            {"journal": "PhRvX", "all_volume": True},{"journal": "PhyOJ", "all_volume": True},
            {"journal": "RvMP", "all_volume": True},
        ]},
        {'name': 'APSE3', 'extension_pattern': '.tagged', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal": "APSMEET", "all_volume": True},
        ]},
        {'name': 'ARAnAhtml', 'extension_pattern': '.html', 'reference_service_endpoint': '/text', 'matches': [
            {"journal":"ARA+A", "volume_begin":44, "volume_end":45}
        ]},
        {'name': 'AREPShtml', 'extension_pattern': '.html', 'reference_service_endpoint': '/text', 'matches': [
            {"journal":"AREPS", "volume_begin":24, "volume_end":35},
        ]},
        {'name': 'arXiv', 'extension_pattern': '.raw', 'reference_service_endpoint': '/text', 'matches': [
            {"journal": "arXiv", "all_volume": True},{"journal": "OTHER", "volume_string": "Astro2020"},
            {"journal":"ESASP", "all_volume":True},{"journal":"ICRC", "all_volume":True},{"journal":"adap-org", "all_volume":True},
            {"journal":"alg-geom", "all_volume":True},{"journal":"astro-ph", "all_volume":True},{"journal":"chao-dyn", "all_volume":True},
            {"journal":"cmp-lg", "all_volume":True},{"journal":"comp-gas", "all_volume":True},{"journal":"cond-mat", "all_volume":True},
            {"journal":"cs", "all_volume":True},{"journal":"dg-ga", "all_volume":True},{"journal":"funct-an", "all_volume":True},
            {"journal":"gr-qc", "all_volume":True},{"journal":"hep-ex", "all_volume":True},{"journal":"hep-lat", "all_volume":True},
            {"journal":"hep-ph", "all_volume":True},{"journal":"hep-th", "all_volume":True},{"journal":"nlin", "all_volume":True},
            {"journal":"mat-ph", "all_volume":True},{"journal":"math-ph", "all_volume":True},{"journal":"math", "all_volume":True},
            {"journal":"nuc-ex", "all_volume":True},{"journal":"nucl-ex", "all_volume":True},{"journal":"nucl-th", "all_volume":True},
            {"journal":"patt-sol", "all_volume":True},{"journal":"physics", "all_volume":True},{"journal":"q-alg", "all_volume":True},
            {"journal":"q-bio", "all_volume":True},{"journal":"quant-ph", "all_volume":True},{"journal":"solv-int", "all_volume":True},
        ]},
        {'name': 'Blackwell', 'extension_pattern': '.xml', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal":"A+G", "all_volume":True},{"journal":"GeoJI", "all_volume":True},{"journal":"MNRAS", "all_volume":True},
            {"journal":"TellA", "all_volume":True},{"journal":"TellB", "all_volume":True},
        ]},
        {'name': 'CrossRef', 'extension_pattern': '.xref.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'CUP', 'extension_pattern': '.cup.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'EDP', 'extension_pattern': '.edp.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'EGU', 'extension_pattern': '.egu.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'ELSEVIER', 'extension_pattern': '.elsevier.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'ELSEVIERE2', 'extension_pattern': '.xml', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal":"A+C", "all_volume": True},{"journal":"ADNDT", "all_volume": True},{"journal":"APh", "all_volume": True},
            {"journal":"AcAau", "all_volume": True},{"journal":"AcO", "all_volume": True},{"journal":"AcSpA", "all_volume": True},
            {"journal":"AcSpe", "all_volume": True},{"journal":"AdSpR", "all_volume": True},{"journal":"AdWR", "all_volume": True},
            {"journal":"AeoRe", "all_volume": True},{"journal":"AnPhy", "all_volume": True},{"journal":"ApSS", "all_volume": True},
            {"journal":"AstQ", "all_volume": True},{"journal":"AtScL", "all_volume": True},{"journal":"AtmEB", "all_volume": True},
            {"journal":"AtmEn", "all_volume": True},{"journal":"AtmRe", "all_volume": True},{"journal":"CG", "all_volume": True},
            {"journal":"CIBu", "all_volume": True},{"journal":"CNSNS", "all_volume": True},{"journal":"CP", "all_volume": True},
            {"journal":"CPL", "all_volume": True},{"journal":"CRASB", "all_volume": True},{"journal":"CRASE", "all_volume": True},
            {"journal":"CRASP", "all_volume": True},{"journal":"CRGeo", "all_volume": True},{"journal":"CRMec", "all_volume": True},
            {"journal":"CRPhy", "all_volume": True},{"journal":"CSR", "all_volume": True},{"journal":"ChA+A", "all_volume": True},
            {"journal":"ChA", "all_volume": True},{"journal":"CoPhC", "all_volume": True},{"journal":"CoPhR", "all_volume": True},
            {"journal":"Cryo", "all_volume": True},{"journal":"DSR", "all_volume": True},{"journal":"DSR0", "all_volume": True},
            {"journal":"DSRA", "all_volume": True},{"journal":"DSRB", "all_volume": True},{"journal":"DSRI", "all_volume": True},
            {"journal":"DSRII", "all_volume": True},{"journal":"DSROA", "all_volume": True},{"journal":"DyAtO", "all_volume": True},
            {"journal":"E+PSL", "all_volume": True},{"journal":"ECMS", "all_volume": True},{"journal":"ECSS", "all_volume": True},
            {"journal":"ELSEVIER", "all_volume": True},{"journal":"ESF", "all_volume": True},{"journal":"ESRv", "all_volume": True},
            {"journal":"FlDyR", "all_volume": True},{"journal":"GPC", "all_volume": True},{"journal":"GeCoA", "all_volume": True},
            {"journal":"GeoAc", "all_volume": True},{"journal":"Geomo", "all_volume": True},{"journal":"HEDP", "all_volume": True},
            {"journal":"IJAEO", "all_volume": True},{"journal":"IJRPC", "all_volume": True},{"journal":"InPhT", "all_volume": True},
            {"journal":"InfPh", "all_volume": True},{"journal":"JAESc", "all_volume": True},{"journal":"JAEaS", "all_volume": True},
            {"journal":"JAG", "all_volume": True},{"journal":"JASTP", "all_volume": True},{"journal":"JATP", "all_volume": True},
            {"journal":"JAfES", "all_volume": True},{"journal":"JAsGe", "all_volume": True},{"journal":"JCHyd", "all_volume": True},
            {"journal":"JCoPh", "all_volume": True},{"journal":"JCrGr", "all_volume": True},{"journal":"JDE", "all_volume": True},
            {"journal":"JFS", "all_volume": True},{"journal":"JGP", "all_volume": True},{"journal":"JGeo", "all_volume": True},
            {"journal":"JHyd", "all_volume": True},{"journal":"JMMM", "all_volume": True},{"journal":"JMPSo", "all_volume": True},
            {"journal":"JMRB", "all_volume": True},{"journal":"JMS", "all_volume": True},{"journal":"JMagR", "all_volume": True},
            {"journal":"JMoSp", "all_volume": True},{"journal":"JMoSt", "all_volume": True},{"journal":"JNuM", "all_volume": True},
            {"journal":"JPRS", "all_volume": True},{"journal":"JPS", "all_volume": True},{"journal":"JSAES", "all_volume": True},
            {"journal":"JSG", "all_volume": True},{"journal":"JSR", "all_volume": True},{"journal":"JSSCh", "all_volume": True},
            {"journal":"JSV", "all_volume": True},{"journal":"JVGR", "all_volume": True},{"journal":"Litho", "all_volume": True},
            {"journal":"MPDS", "all_volume": True},{"journal":"MSSP", "all_volume": True},{"journal":"MetaM", "all_volume": True},
            {"journal":"MolAs", "all_volume": True},{"journal":"NDS", "all_volume": True},{"journal":"NDSA", "all_volume": True},
            {"journal":"NDSB", "all_volume": True},{"journal":"NDT", "all_volume": True},{"journal":"NIMPA", "all_volume": True},
            {"journal":"NIMPB", "all_volume": True},{"journal":"NIMPR", "all_volume": True},{"journal":"NJSR", "all_volume": True},
            {"journal":"NewA", "all_volume": True},{"journal":"NewAR", "all_volume": True},{"journal":"NuPhA", "all_volume": True},
            {"journal":"NuPhB", "all_volume": True},{"journal":"NuPhS", "all_volume": True},{"journal":"NucIM", "all_volume": True},
            {"journal":"NucIn", "all_volume": True},{"journal":"NucPh", "all_volume": True},{"journal":"OcMod", "all_volume": True},
            {"journal":"OptCo", "all_volume": True},{"journal":"OptFT", "all_volume": True},{"journal":"OptLE", "all_volume": True},
            {"journal":"OptLT", "all_volume": True},{"journal":"OptMa", "all_volume": True},{"journal":"OptT", "all_volume": True},
            {"journal":"P+SS", "all_volume": True},{"journal":"PApPh", "all_volume": True},{"journal":"PCE", "all_volume": True},
            {"journal":"PCEB", "all_volume": True},{"journal":"PDU", "all_volume": True},{"journal":"PEPI", "all_volume": True},
            {"journal":"PQE", "all_volume": True},{"journal":"PhL", "all_volume": True},{"journal":"PhLA", "all_volume": True},
            {"journal":"PhLB", "all_volume": True},{"journal":"PhLRv", "all_volume": True},{"journal":"PhNan", "all_volume": True},
            {"journal":"PhPro", "all_volume": True},{"journal":"PhR", "all_volume": True},{"journal":"Phy", "all_volume": True},
            {"journal":"PhyA", "all_volume": True},{"journal":"PhyB", "all_volume": True},{"journal":"PhyBC", "all_volume": True},
            {"journal":"PhyC", "all_volume": True},{"journal":"PhyD", "all_volume": True},{"journal":"PhyE", "all_volume": True},
            {"journal":"PolSc", "all_volume": True},{"journal":"PrAeS", "all_volume": True},{"journal":"PrOce", "all_volume": True},
            {"journal":"PrPNP", "all_volume": True},{"journal":"PrSS", "all_volume": True},{"journal":"QSRv", "all_volume": True},
            {"journal":"QuRes", "all_volume": True},{"journal":"RaPC", "all_volume": True},{"journal":"ResPh", "all_volume": True},
            {"journal":"RpMP", "all_volume": True},{"journal":"SSCom", "all_volume": True},{"journal":"SSEle", "all_volume": True},
            {"journal":"SSSci", "all_volume": True},{"journal":"SedG", "all_volume": True},{"journal":"SpReT", "all_volume": True},
            {"journal":"SuMi", "all_volume": True},{"journal":"SurSL", "all_volume": True},{"journal":"SurSR", "all_volume": True},
            {"journal":"SurSc", "all_volume": True},{"journal":"Tectp", "all_volume": True},{"journal":"VA", "all_volume": True},
        ]},
        {'name': 'ICARUS', 'extension_pattern': '.raw', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal":"Icar", "all_volume":True},
        ]},
        {'name': 'IOP', 'extension_pattern': '.iop.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'IOPE2', 'extension_pattern': '.xml', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal": "AnPh", "all_volume": True},{"journal": "BJAP", "all_volume": True},
            {"journal": "BiBi", "all_volume": True},{"journal": "BioMa", "all_volume": True},
            {"journal": "CPPM", "all_volume": True},{"journal": "CQGra", "all_volume": True},
            {"journal": "CTM", "all_volume": True},{"journal": "ChJAA", "all_volume": True},
            {"journal": "ChPhL", "all_volume": True},{"journal": "ChPhy", "all_volume": True},
            {"journal": "DSE", "all_volume": True},{"journal": "EAS", "all_volume": True},
            {"journal": "EDP", "all_volume": True},{"journal": "EDPorIOP", "all_volume": True},
            {"journal": "EJPh", "all_volume": True},{"journal": "EL", "all_volume": True},
            {"journal": "EPJAP", "all_volume": True},{"journal": "EPJWC", "all_volume": True},
            {"journal": "ERL", "all_volume": True},{"journal": "EUCAS", "all_volume": True},
            {"journal": "IOP", "all_volume": True},{"journal": "InvPr", "all_volume": True},
            {"journal": "JCAP", "all_volume": True},{"journal": "JGE", "all_volume": True},
            {"journal": "JHEP", "all_volume": True},{"journal": "JInst", "all_volume": True},
            {"journal": "JMiMi", "all_volume": True},{"journal": "JNEng", "all_volume": True},
            {"journal": "JNuE", "all_volume": True},{"journal": "JOpt", "all_volume": True},
            {"journal": "JOptA", "all_volume": True},{"journal": "JOptB", "all_volume": True},
            {"journal": "JP4", "all_volume": True},{"journal": "JPCM", "all_volume": True},
            {"journal": "JPhA", "all_volume": True},{"journal": "JPhB", "all_volume": True},
            {"journal": "JPhC", "all_volume": True},{"journal": "JPhCS", "all_volume": True},
            {"journal": "JPhD", "all_volume": True},{"journal": "JPhE", "all_volume": True},
            {"journal": "JPhF", "all_volume": True},{"journal": "JPhG", "all_volume": True},
            {"journal": "JRP", "all_volume": True},{"journal": "JSMTE", "all_volume": True},
            {"journal": "JSRP", "all_volume": True},{"journal": "JSWSC", "all_volume": True},
            {"journal": "JScI", "all_volume": True},{"journal": "JTurb", "all_volume": True},
            {"journal": "MSMSE", "all_volume": True},{"journal": "MeScT", "all_volume": True},
            {"journal": "Metro", "all_volume": True},{"journal": "NCNS", "all_volume": True},
            {"journal": "NJPh", "all_volume": True},{"journal": "NROA", "all_volume": True},
            {"journal": "NROpt", "all_volume": True},{"journal": "Nanot", "all_volume": True},
            {"journal": "Nonli", "all_volume": True},{"journal": "NucFu", "all_volume": True},
            {"journal": "PApOp", "all_volume": True},{"journal": "PMB", "all_volume": True},
            {"journal": "PPCF", "all_volume": True},{"journal": "PPS", "all_volume": True},
            {"journal": "PPSA", "all_volume": True},{"journal": "PPSB", "all_volume": True},
            {"journal": "PPSL", "all_volume": True},{"journal": "PSST", "all_volume": True},
            {"journal": "PUS", "all_volume": True},{"journal": "PhBio", "all_volume": True},
            {"journal": "PhST", "all_volume": True},{"journal": "PhTec", "all_volume": True},
            {"journal": "PhyEd", "all_volume": True},{"journal": "PhyM", "all_volume": True},
            {"journal": "PhyS", "all_volume": True},{"journal": "PlPh", "all_volume": True},
            {"journal": "PlST", "all_volume": True},{"journal": "QuFin", "all_volume": True},
            {"journal": "QuOpt", "all_volume": True},{"journal": "QuSOp", "all_volume": True},
            {"journal": "RPPh", "all_volume": True},{"journal": "RvPT", "all_volume": True},
            {"journal": "SMaS", "all_volume": True},{"journal": "SeScT", "all_volume": True},
            {"journal": "SuScT", "all_volume": True},{"journal": "TrOS", "all_volume": True},
            {"journal": "WRM", "all_volume": True}, ]},
        {'name': 'IOPE3', 'extension_pattern': '.raw', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal": "CONF", "partial_bibcode":"2000eaa..book"},{"journal": "JPC", "all_volume": True},
        ]},
        {'name': 'IOPFT', 'extension_pattern': '.iopft.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'IPAP', 'extension_pattern': '.ipap.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'JATS', 'extension_pattern': '.jats.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'JLVEnHTML', 'extension_pattern': '.raw', 'reference_service_endpoint': '/text', 'matches': [
            {"journal": "JLVEn", "all_volume": True},
        ]},
        {'name': 'JSTAGE', 'extension_pattern': '.jst.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'LivingReviews', 'extension_pattern': '.living.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'MDPI', 'extension_pattern': '.mdpi.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'MNRAS', 'extension_pattern': '.wiley.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'NATURE', 'extension_pattern': '.nature.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'NATUREE2', 'extension_pattern': '.xml', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal": "NPhS", "all_volume": True},{"journal": "NaPho", "all_volume": True},
            {"journal": "NatCh", "all_volume": True},{"journal": "NatMa", "all_volume": True},
            {"journal": "NatNa", "all_volume": True},{"journal": "NatPh", "all_volume": True},
            {"journal": "Natur", "all_volume": True},
        ]},
        {'name': 'NLM', 'extension_pattern': '.nlm3.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'ObsOCR', 'extension_pattern': '.ocr.txt', 'reference_service_endpoint': '/text', 'matches': [
            {"journal":"Obs", "all_volume":True},
        ]},
        {'name': 'ONCP', 'extension_pattern': '.meta.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'OUP', 'extension_pattern': '.oup.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'PairsTXT', 'extension_pattern': '.pairs', 'reference_service_endpoint': '/text', 'matches': [
            {"journal":"OTHER", "partial_bibcode":"2022arXiv220100358E"},{"journal":"OTHER", "partial_bibcode":"2021arXiv210302369R"},
            {"journal":"OTHER", "partial_bibcode":"2020mmms.book.....R"},{"journal":"OTHER", "partial_bibcode":"2020arXiv200109231W"},
            {"journal":"OTHER", "partial_bibcode":"2020AAS...23515905T"},{"journal":"OTHER", "volume_string":"GitaKumari"},
            {"journal":"OTHER", "partial_bibcode":"2019msme.book"},{"journal":"OTHER", "partial_bibcode":"1937PLMS...42...90W"},
            {"journal":"OTHER", "partial_bibcode":"2012PhDT........75J"},{"journal":"OTHER", "volume_string":"Edwin"},
            {"journal":"OTHER", "partial_bibcode":"2012PhDT.........75J"},{"journal":"OTHER", "volume_string":"IBVS"},
            {"journal":"AUTHOR", "all_volume": True},{"journal":"AcA", "volume_begin":59, "volume_end":90},
            {"journal":"CONF", "partial_bibcode":"2009grb..book"},{"journal":"ESASP", "volume_number":622},
            {"journal":"PSRD", "all_volume": True},{"journal":"ATel", "all_volume": True},
        ]},
        {'name': 'PairsTXTE2', 'extension_pattern': '.isi.pairs', 'reference_service_endpoint': '/text', 'matches': [
            {"journal":"ISI", "all_volume":True},
        ]},
        {'name': 'PairsTXTE3', 'extension_pattern': '.atel.pairs', 'reference_service_endpoint': '/text', 'matches': []},
        {'name': 'PairsTXTE4', 'extension_pattern': '.editor.pairs', 'reference_service_endpoint': '/text', 'matches': []},
        {'name': 'PairsTXTE5', 'extension_pattern': '.pds.pairs', 'reference_service_endpoint': '/text', 'matches': []},
        {'name': 'PASA', 'extension_pattern': '.xml', 'reference_service_endpoint': '/xml', 'matches': [
            {"journal":"PASA", "all_volume":True},{"journal":"ExG", "all_volume":True},
        ]},
        {'name': 'PASJhtml', 'extension_pattern': '.raw', 'reference_service_endpoint': '/text', 'matches': [
            {"journal": "PASJ", "volume_begin": 51, "volume_end": 53},
        ]},
        {'name': 'PASPhtml', 'extension_pattern': '.raw', 'reference_service_endpoint': '/text', 'matches': [
            {"journal": "PASP", "all_volume": True},
        ]},
        {'name': 'PThPhTXT', 'extension_pattern': '.raw', 'reference_service_endpoint': '/text', 'matches': [
            {"journal": "PThPS", "all_volume": True},{"journal": "PThPh", "all_volume": True},
        ]},
        {'name': 'RSC', 'extension_pattern': '.rsc.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'SPIE', 'extension_pattern': '.spie.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'SPRINGER', 'extension_pattern': '.springer.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'ThreeBibsTxt', 'extension_pattern': '.ref.raw', 'reference_service_endpoint': '/text', 'matches': [
            {"journal": "AnRFM", "volume_begin": 34, "volume_end": 37}, {"journal": "ARA+A", "volume_begin": 40, "volume_end": 43},
            {"journal": "ARNPS", "volume_begin": 52, "volume_end": 56},
        ]},
        {'name': 'ThreeBibsTxtE2', 'extension_pattern': '.ref.txt', 'reference_service_endpoint': '/text', 'matches': [
            {"journal": "ARNPS", "volume_begin": 1, "volume_end": 51}, {"journal": "AnRFM", "volume_begin": 1, "volume_end": 33},
        ]},
        {'name': 'ThreeBibsTxtE3', 'extension_pattern': '.refs', 'reference_service_endpoint': '/text', 'matches': [
            {"journal": "ARA+A", "volume_begin": 34, "volume_end": 39}, {"journal": "ARA+A", "volume_number": 47},
        ]},
        {'name': 'UCP', 'extension_pattern': '.ucp.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'VERSITA', 'extension_pattern': '.versita.xml', 'reference_service_endpoint': '/xml', 'matches': []},
        {'name': 'WILEY', 'extension_pattern': '.wiley2.xml', 'reference_service_endpoint': '/xml', 'matches': []},
    ])


    # CREATE TABLE "reference_source" (
    #   "bibcode" varchar(20),
    #   "source_filename" varchar,
    #   "source_create" datetime,
    #   "resolved_filename" varchar,
    #   "parser_name" varchar,
    #   PRIMARY KEY ("bibcode", "source_filename")
    # );
    op.create_table('reference_source',
                    sa.Column('bibcode', sa.String(), nullable=False, primary_key=True),
                    sa.Column('source_filename', sa.String(), nullable=False, primary_key=True),
                    sa.Column('resolved_filename', sa.String(), nullable=False),
                    sa.Column('parser_name', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(('parser_name',), ['parser.name'], ),
    )

    # CREATE TABLE "processed_history" (
    #   "id" integer PRIMARY KEY,
    #   "bibcode" varchar(20),
    #   "source_filename" varchar,
    #   "source_modified" datetime,
    #   "status" varchar,
    #   "date" datetime,
    #   "total_ref" integer,
    #   "resolved_ref" integer
    #   Foreign KEY ("bibcode", "source_filename")
    # );
    op.create_table('processed_history',
                    sa.Column('id', sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
                    sa.Column('bibcode', sa.String(), nullable=False),
                    sa.Column('source_filename', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['bibcode', 'source_filename'], ['reference_source.bibcode','reference_source.source_filename'], ),
                    sa.Column('source_modified', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(('status',), ['action.status'], ),
                    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('total_ref', sa.Integer(), nullable=False),
    )

    # CREATE TABLE "resolved_reference" (
    #   "history_id" integer,
    #   "item_num" integer,
    #   "reference_str" text,
    #   "bibcode" text,
    #   "score" numeric,
    #   "reference_raw" text,
    #   PRIMARY KEY ("history_id", "item_num")
    # );
    op.create_table('resolved_reference',
                    sa.Column('history_id', sa.Integer(), nullable=False, primary_key=True),
                    sa.Column('item_num', sa.Integer(), nullable=False, primary_key=True),
                    sa.Column('reference_str', sa.String(), nullable=False),
                    sa.Column('bibcode', sa.String(), nullable=False),
                    sa.Column('score', sa.Numeric(), nullable=False),
                    sa.Column('reference_raw', sa.String(), nullable=False),
    )

    # CREATE TABLE "compare_classic" (
    #   "history_id" integer,
    #   "item_num" integer,
    #   "bibcode" text,
    #   "score" numeric,
    #   "state" text,
    #   Foreign KEY ("history_id", "item_num")
    # );
    op.create_table('compare_classic',
                    sa.Column('history_id', sa.Integer(), nullable=False),
                    sa.Column('item_num', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['history_id', 'item_num'], ['resolved_reference.history_id','resolved_reference.item_num'], ),
                    sa.Column('bibcode', sa.String(), nullable=False),
                    sa.Column('score', sa.Numeric(), nullable=False),
                    sa.Column('state', sa.String(), nullable=False),
    )

    # temparary table to tell what is the class of arxiv bibcode for verification proposes only
    # created this table directly in postgres
    # CREATE TABLE "arxiv" (
    #   "bibcode" text,
    #   "category" text,
    #   PRIMARY KEY ("bibcode", "category")
    # );



def downgrade():
    op.drop_table('compare')
    op.drop_table('resolved')
    op.drop_table('history')
    op.drop_table('reference')
    op.drop_table('parser')
    op.drop_table('action')
